defaults:
  default_dataset: parkinson_merder

datasets:
  parkinson_merder:
    description: "Dataset Merder (2 kelas: Healthy vs Parkinson)."
    original_dir: "dataset/original/dataset_merder"
    split_dir: "dataset/split/parkinson_merder"
    class_mode: "direct"
    seed: 42
    valid_extensions: [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp"]
    split:
      train: 0.70
      testing: 0.15
      validation: 0.15
    resize:
      train: [224, 224]
      testing: null
      validation: null
    augmentation_options:
      - no_augment
      - augment_on_the_fly

  parkinson_mixing:
    description: "Dataset Mixing (multi-kelas dari spiral/zigzag)."
    original_dir: "dataset/original/dataset_mixing"
    split_dir: "dataset/split/parkinson_mixing"
    class_mode: "direct"
    seed: 42
    valid_extensions: [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp"]
    split:
      train: 0.70
      testing: 0.15
      validation: 0.15
    resize:
      train: [224, 224]
      testing: null
      validation: null
    augmentation_options:
      - no_augment
      - augment_on_the_fly
